FORMAT: 1A
HOST: https://staging.takemobi.com/

# COVID19-Patient-Hospital-Coordination

Backend endpoints for supporting the Patient-Hospital coordination application.

# Group Incoming Patients

## Where should I go? [/patient-hospital-coordination/v2/incoming-patient]

### POST

Given the patient status, return a ranked list of health care facilities that work best for the incoming patients and the healthcare network.

+ Request (application/json)

    + Attributes (PatientRequest, required)

+ Response 200 (application/json)

    + Attributes (PatientResponse, required)
    
+ Response 400

        Bad Request.
        
+ Response 401

        Unauthorized.
        
+ Response 500

        Internal Server Error.


# Group Hospital 

## Hospital Status Report [/patient-hospital-coordination/v2/report/{?hospital_id}/]

### POST

From public health departments, patients, nurses, doctors, anyone at the hospitals to report the status of the healthcare facility.

+ Parameters
    + hospital_id: `123fwe908423` (string, required) - the unique identifier of the hospital.
    
+ Request (application/json)

    + Attributes (HospitalUpdate, required)
  
+ Response 200 (application/json)

    + Attributes (HospitalUpdateStatus, required)
    
+ Response 400

        Bad Request.
        
+ Response 401

        Unauthorized.
        
+ Response 500

        Internal Server Error.
        

## Hospital Overview [/patient-hospital-coordination/v2/hospitals/]

### GET

Get a list of all known hospital.

+ Response 200 (application/json)

    + Attributes 
        + status: `success` (string, required) - status for the request.
        + candidates (array[HospitalOverview], optional) - list of all known hospitals.
    
+ Response 400

        Bad Request.
        
+ Response 401

        Unauthorized.
        
+ Response 500

        Internal Server Error.
        

## Hospital Search [/patient-hospital-coordination/v2/hospitals{?q}]

### GET

Get a list of all matched hospital.

+ Parameters
    + q: `Massachusetts` (string, required) - the keyword for hospital search.
    
+ Response 200 (application/json)

    + Attributes 
        + status: `success` (string, required) - status for the request.
        + candidates (array[HospitalOverview], optional) - list of all known hospitals.
    
+ Response 400

        Bad Request.
        
+ Response 401

        Unauthorized.
        
+ Response 500

        Internal Server Error.
        

## Hospital Details [/patient-hospital-coordination/v2/hospitals/{hospital_id}/]

### GET

Get details of the hospital, identified by the hospital id.

+ Parameters
    + hospital_id: `123fwe908423` (string, required) - the unique identifier of the hospital.

+ Response 200 (application/json)

    + Attributes 
        + hospital (HospitalOverview, optional) - overview of the hospital.
        + status (HospitalStatusReport, optional) - status of the hospital.

+ Response 400

        Bad Request.
        
+ Response 401

        Unauthorized.
        
+ Response 500

        Internal Server Error.
        

## Aggregated Status [/patient-hospital-coordination/v2/aggregated-status{?level,lat1,lng1,lat2,lng2}]

### GET

Get a list of aggregated status for hospitals within the specified bounding box.

+ Parameters
    + level: state (string, required) - the level of granularity for the returned aggregated status. Valid levels are state, county, city and hospital.
    + lat1: 42.0 (number, required) - the latitude of the bottom left corner of the bounding box.
    + lng1: `-71.0` (number, required) - the longitude of the bottom left corner of the bounding box.
    + lat2: 43.0 (number, required) - the latitude of the top right corner of the bounding box.
    + lng2: `-70.0` (number, required) - the longitude of the top right corner of the bounding box.

+ Response 200 (application/json)

    + Attributes 
        + status: `success` (string, required) - status for the request.
        + hospitals (array[AggregatedHospitalStatus], optional) - list of agergated hospital status.
    
+ Response 400

        Bad Request.
        
+ Response 401

        Unauthorized.
        
+ Response 500

        Internal Server Error.


# Group Confirmation 

## Reporter Confirmation [/patient-hospital-coordination/v1/reporter-confirmation{?report_id}]

### GET

Confirm the email provided for the given report.

+ Parameters
    + report_id (string, required) - the unique identifier for the hospital report.

+ Response 200 (application/json)

    + Attributes 
        + status: `success` (string, required) - status for the request.

+ Response 400

        Bad Request.



## Data Structures

### PatientRequest
+ intent (enum, required) - enum for patient intent.
    + Members
        + EXPLORATION
        + NEEDHELP
+ patient_status (enum, required) - enum for patient status.
    + Members
        + NONE
        + MILD
        + SEVERE
        + CRITICAL
+ `covid19_status` (enum, required) - enum for patient's COVID-19 status.
    + Members
        + NONE
        + LIKELY
        + TESTED
        + CONFIRMED
+ `current_location` (Location, required) - the current location of the patient.
+ `filed_at`: 1585338528 (number, required) - the time in unix epoch time this request is filed
+ `immediate_medical_needs` (array[string], optional) - collection of medical support required by the patient now.
+ `patient_prognosis` (array[string], optional) - collection of prognosis estimation for the patient.
+ `patient_demographics` (array[string], optional) - collection of demographics information from the patient.
+ `preferred_hospitals` (array[string], optional) - collection of preferred hospitals by the patient.
+ `preferred_regions` (array[string], optional) - collection of preferred regions for destination hospital.
+ `preferred_types` (array[string], optional) - collection of preferred hospital types.


### PatientResponse
+ status: `success` (string, required) - unique status for the request.
+ candidates (array[HospitalOverview], required) - ranked list of candidate hospitals for the patient.

### Location
+ lat: `42.35031` (number, required) - the latitude of the hospital.
+ lng: `-71.0571` (number, required) - the longitude of the hospital.
+ `time_zone`: `America/New_York` (string, required) - timezone of the hospital.
+ `address_line1`: `464 Massachusetts Ave` (string, optional) - first line of the address for the hospital.
+ `address_line2`: `` (string, optional) - second line of the address for the hospital.
+ `county`: `Middlesec` (string, optional) - county of the address for the hospital.
+ `city`: `Cambridge` (string, optional) - city of the address for the hospital.
+ `state_province`: `Massachusetts` (string, optional) - state or province for the hospital.
+ `postal_code`: `02139` (string, optional) - postal code for the hospital.
+ `country`: `USA` (string, optional) - country of the hospital.


### HospitalUpdate
+ id: `a1111c8c-c720-46c3-8534-2fcdd730040d` (string, required) - unique identifier for the hospital.
+ `report_id`: `a1111c8c-c720-46c3-8534-2fcdd730040d` (string, required) - unique identifier for the report.
+ `filed_at`: 1585338528 (number, required) - the time in unix epoch time this report is filed.
+ `reporter_type` (enum, optional) - enum for the reporter's status.
    + Members
        + UNSPECIFIED
        + PATIENT
        + MEDICAL_WORKER
        + STAFF
        + OFFICIAL
+ email: `123@abc.com` (string, optional) - email for the reporter.
+ `available_beds`: 15 (number, optional) - number of available beds at the hospital now.
+ `available_beds_confidence` (enum, required) - enum for confidence on available bed input.
    + Members
        + UNSPECIFIED
        + GUESS
        + EDUCATED_ESTIMATION
        + CERTAIN
+ `available_corona_beds`: 10 (number, optional) - number of available beds designated for corona patients
+ `corona_beds_confidence` (enum, required) - enum for confidence on corona bed input.
    + Members
        + UNSPECIFIED
        + GUESS
        + EDUCATED_ESTIMATION
        + CERTAIN
+ `available_icu_beds`: 10 (number, optional) - number of available beds designated for ICU patients
+ `icu_beds_confidence` (enum, required) - enum for confidence on icu bed input.
    + Members
        + UNSPECIFIED
        + GUESS
        + EDUCATED_ESTIMATION
        + CERTAIN
+ `available_ventilators`: 5 (number, optional) - number of available ventilators at the hospital now
+ `available_ventilators_confidence` (enum, required) - enum for confidence on available ventilators input.
    + Members
        + UNSPECIFIED
        + GUESS
        + EDUCATED_ESTIMATION
        + CERTAIN
+ `total_ventilators`: 15 (number, optional) - total number of ventilators at the hospital now.
+ `total_ventilators_confidence` (enum, required) - enum for confidence on total ventilators input.
    + Members
        + UNSPECIFIED
        + GUESS
        + EDUCATED_ESTIMATION
        + CERTAIN
+ description: `it is very crowed` (string, optional) - a description for the hospital.
+ `current_number_corona_patients_without_ventilator`: 10 (number, optional) - number of corona patients at hospital not requiring a ventilator yet.
+ `corona_patients_without_ventilator_confidence` (enum, required) - enum for confidence on number of corona patients at hospital not requiring a ventilator input.
    + Members
        + UNSPECIFIED
        + GUESS
        + EDUCATED_ESTIMATION
        + CERTAIN
+ `current_wait_time`: 30 (number, optional) - current wait time for check-in at the hospital now (in seconds).
+ `wait_time_confidence` (enum, required) - enum for confidence on wait time input.
    + Members
        + UNSPECIFIED
        + GUESS
        + EDUCATED_ESTIMATION
        + CERTAIN


### HospitalUpdateStatus
+ status: `success` (string, required) - status for the request. Returns either `success` or some explanation why the update could not be incorporated, e.g. `no corresponding hospital found`.


### HospitalStatusReport
+ `source`: `3 reports` (string, optional) - description of the data source.
+ `beds` (Capacity, optional) - capacity of beds at the hospital now.
+ `icu_beds` (Capacity, optional) - capacity of ICU beds at the hospital now.
+ `corona_beds` (Capacity, optional) - capacity of corona beds at the hospital now.
+ `adult_ventilators` (Capacity, optional) - capacity of adult ventilators at the hospital now.
+ `ecmo` (Capacity, optional) - capacity of ecmo at the hospital now.
+ `current_wait_time_seconds` (Observation, optional) - current wait time for check-in at the hospital now (in seconds).

### Capacity
+ available (Observation, required) - available capacity.
+ used (Observation, required) - used capacity.
+ total (Observation, required) - total capacity.

### Observation
+ value: 10 (number, required) - value of the metric.
+ confidence (enum, required) - confidence of the metric.
    + Members
        + UNSPECIFIED
        + GUESS
        + EDUCATED_ESTIMATION
        + CERTAIN
        

### HospitalOverview
+ id: `a1111c8c-c720-46c3-8534-2fcdd730040d` (string, required) - unique identifier for the hospital.
+ location (Location, required) - the location of the hospital
+ name: `Mass General` (string, required) - the name of the hospital.
+ type: `Short Term Acute Care Hospital` (string, required) - the type of the hospital.
+ photo: `https://lh5.googleusercontent.com/p/AF1QipMckTTCJlA7LhbwA8AgJmCCK-P4ta0SP5uqVnWJ=w408-h306-k-no` (string, optional) - a link to a representative image of the hospital.
+ `travel_information` (TravelInformation, required) - travel information from the provided location to the hospital.


### TravelInformation
+ `travel_distance`: 25000 (number, required) - travel distance from the provided location (in meters).
+ `travel_time`: 1800 (number, required) - travel time from the provided location (in seconds).


### AggregatedHospitalStatus
+ id: `a1111c8c-c720-46c3-8534-2fcdd730040d` (string, required) - unique identifier for the aggregate.
+ name: `MA` (string, required) - name of the aggregate.
+ level: `state` (string, required) - level of aggregation.
+ location (required) - the location of the hospital
    + lat: `42.35031` (number, required) - the latitude of the aggregate.
    + lng: `-71.0571` (number, required) - the longitude of the aggregate.
+ total_hospitals: `444` (number, required) - the total number of hospitals in the aggergate.
+ reporting_hospitals: `222` (number, required) - the total number of hospitals with reported data in the aggergate.
+ beds (AggregateCount, optional) - the longitude of the hospital.
+ `corona_beds` (AggregateCount, optional) - timezone of the hospital.
+ `icu_beds (AggregateCount, optional) - first line of the address for the hospital.
+ `ventilators` (AggregateCount, optional) - second line of the address for the hospital.
+ `ecmo` (AggregateCount, optional) - county of the address for the hospital.
+ `average_wait_time`: `1800` (string, optional) - average check-in wait time at the hospital, in seconds.

### AggregateCount
+ no_data: `13` (number, required) - number of hospitals with no reported data in the aggregate.
+ at_capacity: `35` (number, required) - number of hospitals at capacity in the aggregate.
+ over_capacity: `32` (number, required) - number of hospitals over capacity in the aggregate.
+ under_capacity: `1` (number, required) - number of hospitals under capacity in the aggregate.